### ISSUE TITLE
Is feature for delay needed?

### ISSUE THREAD

**Issue by pdgilbert** [nim65s/aht20#1]
With `delay` now set as the default feature I have my `aht20-display` example compiling again using `stm32f0xx-hal`, `stm32f1xx-hal`, `stm32f3x-hal`, `stm32f4xx-hal`, `stm32f7xx-hal`, `stm32h7xx-hal`, `stm32l0xx-hal`, `stm32l1xx-hal`, and `stm32l4xx-hal`. (See  _actions_ at https://github.com/pdgilbert/rust-integration-testing/actions . ) I will report back when I test if it works on hardware.

I also tried an example with `Aht20NoDelay`. For this I changed my `Cargo.toml` to
```
aht20    = { git = "https://github.com/nim65s/aht20", default-features = false } 
```

and `device.read()` to `device.end_read()`. It compiled but I am not sure of the meaning of _end_read_.

Because of the `Cargo.toml` change I cannot include both examples in my tests. I do not understand the need for the feature gate. There are two separate structures `Aht20` and `Aht20NoDelay`. Why use a feature for this?

**Comment by nim65s** [comment]
Hi @pdgilbert,

Sorry, I didn't see your message. 

I don't remember why I added it, so let's try to remove it and see :)

**Comment by pdgilbert** [comment]
Seems to be compiling fine now without having to change the Cargo.toml. Thanks
